"use client";

import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/component/header";
import Footer from "@/component/footer";
import Loader from "@/component/loader";
import PopupModal from "@/component/PopupModal";
import PromotionalBanner from "@/component/promotional-banner";
import { useState, useEffect } from "react";
import { AnimatePresence, motion } from "framer-motion";
import TopBanner from "@/component/top-banner";

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Set up the loader duration (3 seconds)
    let timer: NodeJS.Timeout;
    
    if (isLoading) {
      timer = setTimeout(() => {
        setIsLoading(false);
      }, 3000);
    }

    return () => {
      if (timer) clearTimeout(timer);
    };
  }, [isLoading]);

  return (
    <html lang="en">
      <body className={`${publicSans.className} antialiased`} suppressHydrationWarning={true}>
        <Loader />
        <AnimatePresence>
          {!isLoading && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
              className="w-full"
            >
              <TopBanner />
              <Header />
              <main>
                {children}
              </main>
               <Footer /> 
              <PopupModal />
            </motion.div>
          )}
        </AnimatePresence>
      </body>
    </html>
  );
}
