# Ngrok Configuration for Celebration Diamond
version: "2"
authtoken: YOUR_AUTHTOKEN_HERE

tunnels:
  celebration-diamond:
    proto: http
    addr: 3000
    subdomain: celebration-diamond
    inspect: true
    bind_tls: true
    host_header: localhost:3000
    
  celebration-diamond-https:
    proto: http
    addr: 3000
    subdomain: celebration-diamond-https
    inspect: true
    bind_tls: true
    host_header: localhost:3000

# Global settings
console_ui: true
console_ui_color: transparent
log_level: info
log_format: logfmt
log: /tmp/ngrok.log

