import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/header";
import Footer from "@/component/footer";
import Loader from "@/component/loader";
import SocialMediaIcons from "@/component/SocialMediaIcons";
import PopupModal from "@/component/PopupModal";
import PromotionalBanner from "@/component/promotional-banner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          suppressHydrationWarning={true}
      >
        <Loader />
        <Header/>
      
          <main>
            {children}
          </main>

          <Footer/>
          <SocialMediaIcons />
          <PopupModal />
       
      </body>
    </html>
  
  );
}